/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as UniverseRouteImport } from './routes/universe'
import { Route as DropsSlugRouteImport } from './routes/drops.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const UniverseRoute = UniverseRouteImport.update({
  id: '/universe',
  path: '/universe',
  getParentRoute: () => rootRouteImport,
} as any)
const DropsSlugRoute = DropsSlugRouteImport.update({
  id: '/drops/$slug',
  path: '/drops/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/manifesto': typeof ManifestoRoute
  '/products': typeof ProductsRoute
  '/universe': typeof UniverseRoute
  '/drops/$slug': typeof DropsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/manifesto': typeof ManifestoRoute
  '/products': typeof ProductsRoute
  '/universe': typeof UniverseRoute
  '/drops/$slug': typeof DropsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/manifesto': typeof ManifestoRoute
  '/products': typeof ProductsRoute
  '/universe': typeof UniverseRoute
  '/drops/$slug': typeof DropsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/archive' | '/manifesto' | '/products' | '/universe' | '/drops/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/archive' | '/manifesto' | '/products' | '/universe' | '/drops/$slug'
  id:
    | '__root__'
    | '/'
    | '/archive'
    | '/manifesto'
    | '/products'
    | '/universe'
    | '/drops/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveRoute: typeof ArchiveRoute
  ManifestoRoute: typeof ManifestoRoute
  ProductsRoute: typeof ProductsRoute
  UniverseRoute: typeof UniverseRoute
  DropsSlugRoute: typeof DropsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universe': {
      id: '/universe'
      path: '/universe'
      fullPath: '/universe'
      preLoaderRoute: typeof UniverseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drops/$slug': {
      id: '/drops/$slug'
      path: '/drops/$slug'
      fullPath: '/drops/$slug'
      preLoaderRoute: typeof DropsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveRoute: ArchiveRoute,
  ManifestoRoute: ManifestoRoute,
  ProductsRoute: ProductsRoute,
  UniverseRoute: UniverseRoute,
  DropsSlugRoute: DropsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
